### ISSUE TITLE
Question: why not using react-navigation for web run ?

### ISSUE THREAD

**Issue by ghost** [drgx/react-native-plus-web#9]
Hi

This is a question, if you don't allow question here, my bad, just close it.

- > Is that impossible to use react-navigation with react-native-for-web ? Why is a separate implementation required ?

**Comment by drgx** [comment]
Hi @ArThoX, 
By the time I'm developing this boilerplate, it's quite hard (react-navigation v1 and v2), no documentation, no clear implementation and the most important point was not support browser history API, so no url handling, every-time we refresh the web, it will return to first screen.
Until my friend develop this [library](https://github.com/Jekiwijaya/react-navigation-browser-history-helpers ) and its quite easy to implement. 

But for react-navigation v3, now it is easier, they support better documentation and they have build-in for web browser navigation  ([link](https://reactnavigation.org/docs/en/web-support.html)). Thanks to @ericvicenti  🎉

Here is the example of react-navigation web that support browser history API https://github.com/react-navigation/web-server-example
 
Actually I'm also planning to update this boilerplate to use the react-navigation v3 but I haven't try it yet. Hopefully I can update this boilerplate soon to use react-navigation v3
If you interested to help me, PR also very welcome here 😃

**Comment by ghost** [comment]
@drgx Thanks for this answer.

In theory react-navigation v3 should be compatible.

In reality I am encountering some issue and so far I am was able to add react-navigation to my react-native-web project !

I'll try to migrate your project to r-n v3 and see if I encounter the same issues...

**Comment by drgx** [comment]
Cool @ArThoX , yup just want to make sure that your web project support the url handling, since that feature is a basic feature for web 👍 

Thanks I'll be waiting for your contribution!

If you interested to try other navigation, I just find this [navigation](https://github.com/winoteam/react-router-navigation), its pretty dope, but haven't try it yet. 

I'm also waiting @vincentriemer new experimental navigation its super cool https://twitter.com/vincentriemer/status/1081341451991240705?s=09

**Comment by drgx** [comment]
I'm closing this issue thanks!
